[package]
name = "pick-one"
version = "1.0.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
license = "MIT"
repository = "https://github.com/ashleygwilliams/rust-pick-one"

[dependencies]
rand = "0.3"
